### ISSUE TITLE
Getting UnicodeEncodeError

### ISSUE THREAD

**Issue by JacoboGuijar** [labteral/bluebird#2]
Trying to execute this query:
```
query = {
    'fields': [
        {'items': ['Comunicado Oficial:'], 'from' : 'realmadrid'}
    ],
    
}
tweets = BlueBird().search(query)
for tweet in tweets:
    print(tweet["full_text"])
```

I am getting this:
```
Traceback (most recent call last):
  File "c:\Users\jacob\OneDrive\Escritorio\Futbol & Python friends4ever\vikingos.py", line 16, in <module>
    print(tweet["full_text"])
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 41-42: character maps to <undefined>
```

Any idea on how to solve it?

**Comment by brunneis** [comment]
Hi @JacoboGuijar,

Maybe it's related with the shell you are using and unsupported characters (e.g., emojis). What happens if you dump the content to a file instead? I don't have Windows installed to try it there. I've just ran it successfully on MacOS.
