### ISSUE TITLE
Parsing issue 

### ISSUE THREAD

**Issue by pvwalke** [labteral/bluebird#3]
Traceback (most recent call last):
  File "sample_followers.py", line 3, in <module>
    for username in BlueBird().get_followers('WalkePrathamesh'):
  File "/usr/local/lib/python3.8/dist-packages/bluebird/scraper.py", line 579, in get_followx
    root = document_fromstring(content)
  File "/usr/local/lib/python3.8/dist-packages/lxml/html/__init__.py", line 761, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Fix: 
root = document_fromstring(bytes(content, encoding='utf-8')) in File "/usr/local/lib/python3.8/dist-packages/lxml/html/init.py", line 761

**Comment by brunneis** [comment]
Thanks @pvwalke!
